-- In this file we insert only verbs and verbs tenses


-- insert verbs regular irregular
INSERT INTO verbs (verb, type) VALUES
--regular verbs 
('agree','regular'),
('answer','regular'),
('apologize','regular'),
('ask','regular'),
('awaken','regular'),
('breathe','regular'),
('brush','regular'),
('call','regular'),
('care','regular'),
('change','regular'),
('clean','regular'),
('clear','regular'),
('close','regular'),
('cook','regular'),
('cross','regular'),
('cry','regular'),
('dance','regular'),
('deliver','regular'),
('describe','regular'),
('desire','regular'),
('die','regular'),
('disagree','regular'),
('disappear','regular'),
('dislike','regular'),
('end','regular'),
('enjoy','regular'),
('establish','regular'),
('exchange','regular'),
('fail','regular'),
('fear','regular'),
('guess','regular'),
('hate','regular'),
('help','regular'),
('invite','regular'),
('join','regular'),
('kill','regular'),
('learn','regular'),
('lie','regular'),
('like','regular'),
('listen','regular'),
('live','regular'),
('eat','regular'),
('look','regular'),
('love','regular'),
('miss','regular'),
('move','regular'),
('study','regular'),
('walk','regular'),
('want','regular'),
('work','regular'),
('worry','regular')

--irregular verbs
,('be','irregular'),
('bear','irregular'),
('become','irregular'),
('begin','irregular'),
('break','irregular'),
('bring','irregular'),
('build','irregular'),
('buy','irregular'),
('choose','irregular'),
('come','irregular'),
('do','irregular'),
('drink','irregular'),
('drive','irregular'),
('eat','irregular'),
('feed','irregular'),
('feel','irregular'),
('find','irregular'),
('forbid','irregular'),
('forget','irregular'),
('get','irregular'),
('give','irregular'),
('go','irregular'),
('have','irregular'),
('hear','irregular'),
('hide','irregular'),
('keep','irregular'),
('know','irregular'),
('lead','irregular'),
('learn','irregular'),
('lose','irregular'),
('make','irregular'),
('mean','irregular'),
('meet','irregular'),
('pay','irregular'),
('put','irregular'),
('read','irregular'),
('ride','irregular'),
('run','irregular'),
('say','irregular'),
('see','irregular'),
('sell','irregular'),
('send','irregular'),
('sleep','irregular'),
('speak','irregular'),
('take','irregular'),
('tell','irregular'),
('think','irregular'),
('wake','irregular'),
('win','irregular'),
('write','irregular');

-- verbs tenses
INSERT INTO tenses (name) VALUES
('simple present'),('simple past'),('simple future'),
('present continuous'),('past continuous'),('future continuous'),
('present perfect simple'),('past perfect simple'),('future perfect simple'),
('present perfect continuous'),('past perfect continuous'),('future perfect continuous'),
('present perfect continuous'),('past perfect continuous'),('future perfect continuous');


